name: Noteflix
title: Noteflix | Just Noteflix and read.
description: Noteflix is originally based on Jekflix by Thiago 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: sigidpam@outlook.com
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
#  - title: Feed
#    url: /feed.xml
